sudo: required
services:
  - docker

before_install:
  - docker build -t marcelolandivar/react-test -f ./client/Dockerfile.dev ./client
# add more images in case they need to be tested
script:
  - docker run -e CI=true marcelolandivar/react-test npm test

after_success:
  - docker build -t marcelolandivar/multi-client ./client
  - docker build -t marcelolandivar/multi-nginx ./nginx
  - docker build -t marcelolandivar/multi-server ./server
  - docker build -t marcelolandivar/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push marcelolandivar/multi-client
  - docker push marcelolandivar/multi-nginx
  - docker push marcelolandivar/multi-server
  - docker push marcelolandivar/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-1'
  app: 'multi-docker'
  env: 'MultiDocker-env-1'
  bucket_name: 'elasticbeanstalk-eu-west-1-836540728561'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY